### PR TITLE
README: Add missing `install`

### PR DESCRIPTION
**Pull request by sils**
Cheers :)

### CODE REVIEW

**Comment by cuducos** [comment]
Oops… tks ; )

**Comment by sils** [comment]
@cuducos btw. is there something like https://github.com/miracle2k/django-assets/issues/88 that I just didn't find?

**Comment by cuducos** [comment]
Not sure aboug what you mean. As this is just a filter, whenever you run `python manage.py assets build` or `python manage.py assets watch` all bundles (including Elm) will be processed… usually I choose to `watch` for changes (leaving the watcher AND the server running for dev purposes).

**Comment by sils** [comment]
Ah thanks - I was hoping we could have the watch thing running
automatically on the runserver command somehow.

**Pull request merged**
